### ISSUE TITLE
签到是怎么获取的，想知道下思路，我也写了个我学校的，但是不知道获取签到没啥思路

### ISSUE THREAD

**Issue by FuckAnyProblem** [superBiuBiuMan/positionForwechat#2]

**Comment by superBiuBiuMan** [comment]
他签到就做了前端校验，后端不传入签到参数都可以。你可能比较疑惑怎么抓包参数，目前抓包的话不知道电脑为手机提供代理在免root下可不可以，或者手机安装httpCanary或者vnet还抓不抓得到了

**Comment by FuckAnyProblem** [comment]
我知道咋回事了 我学校这边签到只能在图书馆里面签 网页端接口已经关闭了
